version: '3.4'

services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: dotnet-app-db
    volumes:
      - db-volume:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=P@55w0rd

volumes:
  db-volume:
    name: dotnet-app-db-volume
