FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy sln project to the build folder
COPY DotnetApp.sln ./

# Copy csproj
COPY Common/*.csproj /app/Common/
COPY DataAccess/*.csproj /app/DataAccess/
COPY Api/*.csproj /app/Api/

# Copy test csproj
COPY Common.Tests/*.csproj /app/Common.Tests/
COPY DataAccess.Tests/*.csproj /app/DataAccess.Tests/
COPY Api.Tests/*.csproj /app/Api.Tests/

# Copy integration test csproj
COPY Api.IntegrationTests/*.csproj /app/Api.IntegrationTests/

# Restore dependencies
WORKDIR /app
RUN dotnet restore

# Copy everything else
COPY . ./

WORKDIR /app/Api.IntegrationTests
# Copy scripts
COPY Scripts/wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

COPY Scripts/integration-tests-pipeline.sh ./
RUN chmod +x integration-tests-pipeline.sh

ENV API_DB_ENV=DockerCompose

# Execute tests
CMD ["/bin/sh", "-c", "/app/Api.IntegrationTests/integration-tests-pipeline.sh"]