version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        app_build_profile: Debug
    container_name: api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:5000
    links:
      - db
    depends_on:
      - db

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: dotnet-app-db
    volumes:
      - db-volume:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=P@55w0rd

volumes:
  db-volume:
    name: dotnet-app-db-volume
