using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace Api.DTO.Auth
{
    /// <summary>
    ///     DTO for the returning JWT to te client.
    /// </summary>
    [SuppressMessage("ReSharper", "MemberCanBePrivate.Global")] // used as DTO
    [SuppressMessage("ReSharper", "UnusedAutoPropertyAccessor.Global")] // used as DTO
    public class TokenDto
    {
        public TokenDto(string token, DateTime expires)
        {
            Token = token;
            Expires = expires;
        }

        /// <summary>
        ///     JWT generated by the application.
        /// </summary>
        [Required]
        public string Token { get; }

        /// <summary>
        ///     DateTime when the token expires.
        /// </summary>
        [Required]
        public DateTime Expires { get; }
    }
}